### ISSUE TITLE
Camera exposure

### ISSUE THREAD

**Issue by ChristophTobler** [zehortigoza/aero-optical-flow#11]
The camera exposure is way to high which makes it impossible to test outside during the day (image is completely white). We definitely need the possibility to set the exposure of the camera manually. Even better would be an auto exposure.

**Comment by zehortigoza** [comment]
Still working on this one, the exposure api in V4L2 did not worked for this camera/atomisp, still debugging to see if I can make this to work.

**Comment by zehortigoza** [comment]
Added support in this commit https://github.com/zehortigoza/aero-optical-flow/commit/c1c6aec3f19afb103f24062b4f00af74ccef42fb
