### ISSUE TITLE
px4flow module integration problem

### ISSUE THREAD

**Issue by trgiman** [zehortigoza/aero-optical-flow#20]
Hi all,

We have connected px4flow module to telemetry port of Intel Aero. Previously we connected in the same way on the same port Garmin Lidar. We are absolutely sure, that SDA and SCL and VDD and GND cables are correct. px4flow module works well when connected trough USB port to QGControl 3.3.0 and we uploaded firmware and performed calibration....

Current configuration of Intel RTF is:

BIOS_VERSION = Aero-01.00.13
OS_VERSION = Poky Aero (Intel Aero Linux Distro) 1.6.1 (pyro)"
AIRMAP_VERSION = 1.8
FPGA_VERSION = 0xc2
AeroFC firmware version = 1.7.3

Following are the issues:

1th try: We were following guide for connecting px4flow to Intel RTF according Intel Instructables. But after uploading the custom PX4 firmware file aerofc-v1_px4flow.px to Aero FC QGround 3.3.0 is not able to connect, also mavlink_shell.py command does not allows us connect to flight controller nsh shell. For AeroFC fmw version 1.7.3 works everything well.

2nd try: when in nsh AeroFC shell and when we use 1.7.3 firmware and when we apply command px4flow start. It just says "scanning I2C buses for device..than it stops" When we run px4flow info. It says driver not running.

3rd try: We compiled our own PX4 firmware for AeroFC and added drivers/px4flow into the nuttx_aerofc-v1_default.cmake...but  results are the same as in point 2.

Could you please provide us with correct configuration for point 3 or 1,2? At the end of the day we would like to use both Garmin Lidar and px4flow at once to improve quality of flight without GPS.

Thank you,
Martin

**Comment by zehortigoza** [comment]
This is not the right place for this issue, you should open a issue in PX4 or in meta-intel-aero.

Telemetry pins
5V
UART TX
UART RX
I2C CLK
I2C SDA
GND

I would not recomend to use the firmware from the Instructables as it is really old and uses a different baudrate(that is why QGroundControl can not connect to it)
There is the px4flow driver in regular Aero PX4 firmware?! that is odd.
Make sure you are using the Aero-rtf firmware that comes with the Aero image.
Just to make sure, do not keep the USB cable connected to PX4Flow when connecting it to Aero.

Other option would be connect the PX4Flow using UART, there is a I2C port and UART port in it. You can connect the UART port to the UART RX and UART TX of the telemetry port but you need to change the baudrate of that port in PX4, right now it is runing at 57600 and PX4Flow runs at 115200.

**Comment by trgiman** [comment]
Hi Jose,

Thanks. I will reopen issue in other section an try your recommendations. 
Also, there is no PX4flow driver in standard Aero-rtf firmware.
I added px4flow driver into  added drivers/px4flow into the nuttx_aerofc-v1_default.cmake and complied PX4 flow for nuttx_aerofc-v1_default and than uploaded by using command  make nuttx_aerofc-v1_default upload. Note I am using PX4 source ver: 1.7.3 from github.

**Comment by sugnanprabhu** [comment]
@trgiman px4flow px4flow driver is not started by default for aero.

https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rcS#L682

Try adding the following.

```
+       if ver hwcmp AEROFC_V1
+       then
+               px4flow start &
+       fi

```

If you still face any issue open an issue open an issue on meta-intel-aero

**Comment by sluthra1** [comment]
Hello, I am a little confused on what was done above to get px4flow working, can someone clarify the specific  steps they took to get px4flow working?

**Comment by sugnanprabhu** [comment]
@sluthra1 two changes are required to get the px4flow working on the aero.
* px4flow was not started by default for aero which is done as part of rcS change
* Another is px4flow sensor I2C slave address was not looked on TELEMETRY port, which is fixed as part of the following patch.
https://github.com/PX4/Firmware/pull/8994

Please also check following for more details.
https://github.com/intel-aero/meta-intel-aero/issues/320

**Comment by sluthra1** [comment]
@sugnanprabhu Thank you for the quick response, sorry I am very new to working with PX4 (on an intel aero), how exactly do I go about making the res change, and applying the Firmware patch you specified above (my experience with PX4 is limited to the specific steps given in the intel aero setup guide).

**Comment by sugnanprabhu** [comment]
@sluthra1 Please refer the following link for more details on closing the source and build it.
https://dev.px4.io/en/setup/building_px4.html

**Comment by sluthra1** [comment]
@sugnanprabhu. Thank you so much! So if I make the above changes in the cloned from github firmware and build according to the link I should be good to go?

**Comment by sluthra1** [comment]
@sugnanprabhu I followed all the above steps and optical flow readings came in but for some reason position control mode always gets rejected. Any thoughts?

**Comment by sluthra1** [comment]
@sugnanprabhu do I need to enable the driver in the make file?

**Comment by sugnanprabhu** [comment]
@sluthra1 if you are able to see the px4flow reading in the QGC, then the px4flow is enabled successfully.

> position control mode always gets rejected

Check the following link,
https://dev.px4.io/en/tutorials/optical_flow.html
Hope you have enabled the px4flow in EKF2 params EKF2_AID_MASK
If you still face any issue, you can check with the px4 community.
