### ISSUE TITLE
Using teraranger one with intel aero optical flow

### ISSUE THREAD

**Issue by mubaarik** [zehortigoza/aero-optical-flow#21]
I have been trying to connect a [teraranger One](https://www.terabee.com/wp-content/uploads/files/TeraRanger_to_Pixhawk_Connection_Instructions.pdf) to the intel aero for the optical-flow vertical distance sensing. The set up is similar to the one [here](https://docs.px4.io/en/flight_controller/intel_aero.html) with the Lidar Lite3 using the compass port. I am using [this adaptor](http://www.teraranger.com/product/adapters-for-oneduo/) to connect the sensor to the flight controller and powering it from the battery. 

The sensor turns on as the LEDs show. I have probed the SDA and SCL lines using oscilloscope and I can see data on the lines. Of course I didn't decode the data to see what's happening if anything but yes.

However QGroundcoontrol doesn't show connection. Then I have used the px4 console running the following commands with corresponding outputs 
```
nsh> teraranger status

error: [teraranger] driver not running
```
```
nsh> teraranger start

ERROR [teraranger] driver start failed.
```
After that I am not sure how to proceed. Any suggestions?

Thanks

**Comment by zehortigoza** [comment]
So are you trying to connect this range sensor to the USB port using this? http://www.teraranger.com/product/adapters-for-oneduo/
If so the USB is not connected to the flight controller, it is connected to Aero compute board, so you can write a linux application to read that port and send mavlink messages to the flight controller with the distance data.

Or you should connect it to the telemetry port like in the like you send but you will need to add support to PX4_I2C_BUS_EXPANSION1(telemetry I2C is this one) in teraranger driver, see the Lidar Lite3 driver. Or adding a I2C splitter to the external compass port it should work PX4_I2C_BUS_EXPANSION but I would recommend you keep just the external compass in that port for performance reasons.

**Comment by zehortigoza** [comment]
Closing here and copying the answer to meta-intel-aero
