### ISSUE TITLE
Confusion with integrated_x and integrated_y

### ISSUE THREAD

**Issue by mmorningstar9** [zehortigoza/aero-optical-flow#22]
Do the integreated_x and integrated_y msgs take the gyro rotation information into account? or is it purely based on the image data?

**Comment by zehortigoza** [comment]
Gyro data comes from FC so it takes in care the rotation that FC needs.
But looks like inside PX4 the mavlink_optical_flow_rad message is rotated again: https://github.com/intel-aero/aero-optical-flow/commit/527f293f4b999eb1cd8e44a1e97a52ae65bf2cfb
@ChristophTobler can explain better

**Comment by ChristophTobler** [comment]
@mmorningstar9 `integrated_x` and `integrated_y` only takes the image information into account. The `optical_flow_rad` msg contains the (integrated) gyro values that then the autopilot (PX4 Firmware) uses to calculate the horizontal translation (with range data).
