### ISSUE TITLE
Noise on Lidar Lite V3

### ISSUE THREAD

**Issue by victordias2000** [zehortigoza/aero-optical-flow#24]
Hello,

We've followed the steps from this thread regarding adding a Lidar Lite V3 into the mix. However, we're noticing significant noise from the distance sensor:

![image](https://user-images.githubusercontent.com/25933443/39671089-93803824-5109-11e8-9b88-49893972148b.png)

All the spikes in the picture are due to noise, which varies from 5m up to 160m. During this period the drone never went beyond 4m (which is the steady red line if we exclude the noise).

Just in case, we've added a capacitor (1000 micro Farad, 12V) as suggested on the Garmin manual.

Are you experiencing similar reading patterns? any suggestion on how to improve it?

Kind regards,
Victor.

**Comment by zehortigoza** [comment]
We got this noise too, most of the time the control loop will just filter it out but sometimes it causes the altitude hovering to change. We tried to fix this but without success, our recommendation is to switch to LeddarOne that is UART lidar were we don't have any noise problems.

**Comment by victordias2000** [comment]
Thanks Jose,

But in this case, Intel should stop claiming that Lidar Lite has been tested successfully on the RTF drone. We bought this sensor due to the recommendation.

Kind regards,
Victor

**Comment by zehortigoza** [comment]
true, I will update the documentation.

**Comment by zehortigoza** [comment]
Instructions if you need: https://github.com/PX4/px4_user_guide/pull/215
