### ISSUE TITLE
OPTICAL_FLOW_RAD not getting distance

### ISSUE THREAD

**Issue by rr2-ip** [zehortigoza/aero-optical-flow#25]
Hi,

We have exactly the same issue and setup as here <https://github.com/intel-aero/aero-optical-flow/issues/23> (except we are using the LeddarOne range finder).
We had already set EKF2_HGT_MODE = 2, even after setting this parameter again (and rebooting the drone), the issue still remains.

Here is the output we got from aero-get-version.py:
BIOS_VERSION = Aero-01.00.13
OS_VERSION = Ubuntu 16.04.5 LTS"
AIRMAP_VERSION = unknown
PFGA_VERSION = 0xc2
AeroFC firmware version = 1.8.0

We have set SENS_EN_LEDDAR1 = 1, EKF2_AID_MASK = 2 and EKF2_HGT_MODE = 2.
The LeddarOne appears to be functioning correctly as we can see the distance under DISTANCE_SENSOR in MAVLink Inspector.

![issue](https://user-images.githubusercontent.com/40975580/43561565-e6471ff0-965a-11e8-9666-3ed076b6ab17.png)

How can we get OPTICAL_FLOW_RAD to use the distance published by the LeddarOne?

**Comment by zehortigoza** [comment]
As explained in https://github.com/intel-aero/aero-optical-flow/issues/23 that is the expected behavior for this setup, the distance in OPTICAL_FLOW_RAD is only filled in PX4Flow because it computes optical-flow and also have a sonar connected to the same microcontroller.
