### ISSUE TITLE
fail on startup

### ISSUE THREAD

**Issue by ChristophTobler** [zehortigoza/aero-optical-flow#4]
@zehortigoza It can happen that the flow doesn't start because of:
```
[Error] BMI160 init error
```
or it starts but prints
```
[Error] BMI160 Unable to open ./bmi160.param
```
Any ideas?

**Comment by zehortigoza** [comment]
About:
> [Error] BMI160 init error

I'm still investigating it.

> [Error] BMI160 Unable to open ./bmi160.param

Run aero-optical-flow once with "-b" and keep the drone in a flat surface it will save the gyro offsets to this file.

**Comment by ChristophTobler** [comment]
ah ok 👍

**Comment by samacluka** [comment]
@zehortigoza The program still fails on start up for me. It gives me the following output:

Parameters:
	camera_device=/dev/video2
	camera_id=1
	camera_width=320
	camera_height=240
	crop_width=128
	crop_height=128
	flow_output_rate=15
	mavlink_tcp_port=5760
	focal_length_x=216.667694
	focal_length_y=216.245697
	bmi160_calibrate=0
	parameter_folder=.
[Error] Getting exposure: Invalid argument
[Error] Unable to initialize camera

**Comment by zehortigoza** [comment]
@samacluka You need to build a Intel Aero image with this changes: https://github.com/intel-aero/meta-intel-aero-base/pull/7

Or you can remove the exposure stuff from the code.

Just a reminder that the aero-optical-flow is still not working properly test/improve it at your own risk.
