### ISSUE TITLE
abrupt stop

### ISSUE THREAD

**Issue by ChristophTobler** [zehortigoza/aero-optical-flow#5]
The flow app stops mostly after some time (sometimes earlier, sometimes later).
@zehortigoza Have you had the same issue?

**Comment by zehortigoza** [comment]
I had some times but every-time that it happens I don't have GDB connected to debug, 99% sure that is because badly ported ISP driver.
I will try some workarounds to restart the video streaming after 2 times of the period between 2 frames.

**Comment by zehortigoza** [comment]
Workaround implemented the problem is the atomisp driver, as we already have a issue on https://github.com/intel-aero/meta-intel-aero to update the atomisp driver I'm closing this issue.

**Comment by ChristophTobler** [comment]
Is this still being tracked? I can't find the issue in https://github.com/intel-aero/meta-intel-aero/issues

**Comment by zehortigoza** [comment]
> Is this still being tracked? I can't find the issue in https://github.com/intel-aero/meta-intel-aero/issues

Is this one: https://github.com/intel-aero/meta-intel-aero/issues/64
