### ISSUE TITLE
3 OPTICAL_FLOW_RAD topics in QGC

### ISSUE THREAD

**Issue by ChristophTobler** [zehortigoza/aero-optical-flow#9]
If I run the aero-optical-flow app I get 3 `OPTICAL_FLOW_RAD` in QGC. One has no data at all, one runs at a low frequency and one seems good. Not sure how the autopilot handles this...
![qgc-aero-3flow](https://cloud.githubusercontent.com/assets/14769636/25625469/deef6f98-2f5c-11e7-95e7-d15d127ed867.png)

**Comment by zehortigoza** [comment]
As this MAVlink message do not have a target system id it is broadcast, so the M100 is aero-optical-flow sending the messages and QGC and PX4 is receiving it, this is the one at a good frequency, the M1 is PX4 broadcasting the the received optical flow data at 1Hz(grep for 'configure_stream("OPTICAL_FLOW_RAD", 1.0f);')

About the duplicated M100, I'm not sure but after changing the component id(e24ab2a28834339debb754c91fb2c701d16afc08) in aero-optical-flow, now it only have topic with M100.
